### ISSUE TITLE
微信代码转换bug

### ISSUE THREAD

**Issue by XiaoCaiTouYa** [mdnice/sitdown#11]
## 微信代码片段转换会出现问题，示例文章：
55个提高你CSS开发效率的必备片段：[55个提高你CSS开发效率的必备片段](https://mp.weixin.qq.com/s?__biz=MzAwNjI5MTYyMw==&mid=2651498295&idx=1&sn=d87bc2c13b716cce83ff245ce5578a43&chksm=80f1aeffb78627e9857d04cbb125bc162e4c484ccbddc695c4fcd2b543f51bd9950a16c75303&mpshare=1&scene=1&srcid=&sharer_sharetime=1585006538111&sharer_shareid=3692aac44781ba04af20706a116d0794&key=346c979da5a4c9bec0444e2f6738c8cec8e79c360ea7542ba5355ff22b2f37cd507c41d2a8b1500d8e14965aa872184afc2c48b48792b3fecab18db7d789aacbcb621415c459e1d68bb845ec75c90b42&ascene=1&uin=MTM1ODY4ODI2Mg%3D%3D&devicetype=Windows+10&version=62080085&lang=zh_CN&exportkey=A2BjqDkaUN5vCtH1diqI1vs%3D&pass_ticket=xFFYvjbxoXzaWVc2%2Br6hsPXpivN8KUprnhyMYpjmBkBlvBWN5y5csmrzEJ%2B9T0%2Bk)

**Comment by LinFeng1997** [comment]
@XiaoCaiTouYa xiao 请问这篇微信文章是用什么编辑器生成的，应该不是 mdnice 吧？
看了这篇文章的代码块 DOM，比标准的代码块 DOM 结构多了个 section：
![image](https://user-images.githubusercontent.com/16188742/77437859-1b0bfa00-6e20-11ea-9f28-6df8c88c7349.png)

用 mdnice 生成的代码块是标准的格式：
![image](https://user-images.githubusercontent.com/16188742/77437976-3e36a980-6e20-11ea-8ff9-f426b72d2956.png)

**Comment by XiaoCaiTouYa** [comment]
好吧，我以为是所有的微信文章都能转换成 markdown 呢

**Comment by LinFeng1997** [comment]
@XiaoCaiTouYa 不过我们是支持转换规则自定义拓展的，你可以针对这种非标准格式开发一个插件：https://sitdown.mdnice.com/zh-hans/#%E8%A7%84%E5%88%99%E6%8B%93%E5%B1%95
