### ISSUE TITLE
排版复杂的文章转换出奇怪的内容🙃

### ISSUE THREAD

**Issue by luluxing3** [mdnice/sitdown#12]
https://mp.weixin.qq.com/s/4T6OD2Hr5MzNI0j-mT3e-g

转换结果如下：
![image](https://user-images.githubusercontent.com/23072928/77919608-fa381e80-72cf-11ea-83c7-f94b616917b2.png)

右边栏可以正常显示，但是左边的md很奇怪，无法编辑。

**Comment by LinFeng1997** [comment]
@luluxing3 是不是 4.2 那块的代码块？

**Comment by LinFeng1997** [comment]
@luluxing3 @sitdown/wechat 1.1.4 已支持
