### ISSUE TITLE
正文无法转换且图片无法显示

### ISSUE THREAD

**Issue by luluxing3** [mdnice/sitdown#16]
https://mp.weixin.qq.com/s/UL3mK9Knr6hpmy11EBBvVQ

转换结果如下：
![image](https://user-images.githubusercontent.com/23072928/80956015-f2215080-8e32-11ea-8faf-d64ae42ec675.png)

**Comment by LinFeng1997** [comment]
因为微信图片做了防盗链，建议上传到自己的图床替换链接。
