### ISSUE TITLE
highlight.js 加载代码的部分没有转换

### ISSUE THREAD

**Issue by dear-lizhihua** [mdnice/sitdown#8]
https://lodash.com/docs/
https://github.com/lodash/lodash.com/blob/master/docs/4.17.15.html

![image](https://user-images.githubusercontent.com/15142680/75640706-ebc6fa80-5c70-11ea-9a3c-c2649d6a83d9.png)
![image](https://user-images.githubusercontent.com/15142680/75640851-4d876480-5c71-11ea-8313-6ccba2456764.png)

**Comment by LinFeng1997** [comment]
和 highlight.js 官网的 html 结构对比了一下，还有些不一样：
![image](https://user-images.githubusercontent.com/16188742/75882107-766b4d80-5e5b-11ea-8087-f50d4bfbf9ba.png)

highlight.js 官网的 html 基本符合 gfm 规范，可以转：
![image](https://user-images.githubusercontent.com/16188742/75882244-bcc0ac80-5e5b-11ea-9217-1dc586d903a5.png)
